# Generated by Django 3.2.9 on 2021-11-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile/default.jpg', upload_to='profile/%Y/%m/%d/'),
        ),
    ]
