# Generated by Django 3.2.9 on 2021-11-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile/default.jpg', upload_to='profile/%Y/%m/%d/'),
        ),
    ]
