# Generated by Django 3.2.4 on 2021-06-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doshop', '0004_alter_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specialـprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
