# Generated by Django 3.2.4 on 2021-06-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doshop', '0005_product_specialـprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
